In [ ]:
#Задание 1

In [8]:
import numpy as np
a = np.array([[1, 6], 
              [2, 8 ], 
              [3, 11],
              [3, 10],
              [1, 7]])
print(a)
mean_a = a.mean(axis=0)
print(mean_a)


[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
[2.  8.4]


In [ ]:
#Задание 2

In [10]:
import numpy as np
a = np.array([[1, 6], 
              [2, 8 ], 
              [3, 11],
              [3, 10],
              [1, 7]])
mean_a = a.mean(axis=0)
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [ ]:
#Задание 3

In [15]:
import numpy as np
a = np.array([[1, 6], 
              [2, 8 ], 
              [3, 11],
              [3, 10],
              [1, 7]])
mean_a = a.mean(axis=0)
a_centered = a - mean_a
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1])
print(a_centered_sp)
N = a.shape[0]
d = a_centered_sp/(N-1)
print(d)

8.0
2.0


In [ ]:
#Задание 4

In [16]:
import numpy as np
a = np.array([[1, 6], 
              [2, 8 ], 
              [3, 11],
              [3, 10],
              [1, 7]])
m=np.transpose(a)
print(m)
m_cov = np.cov(m)
print(m_cov)


[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]
[[1.  2. ]
 [2.  4.3]]
